var paper_login;
paper_login =  "CODE:";
paper_login +=  "SET !REPLAYSPEED MEDIUM" + "\n"; 
paper_login +=  "SET !ERRORIGNORE NO" + "\n"; 
paper_login +=  "SET !EXTRACT_TEST_POPUP NO" + "\n"; 
paper_login +=  "ONDIALOG POS=1 BUTTON=OK CONTENT=" + "\n"; 
paper_login +=  "TAB OPEN" + "\n"; 
paper_login +=  "TAB T=2" + "\n"; 
paper_login +=  "TAB CLOSEALLOTHERS" + "\n"; 
paper_login +=  "TAB T=1" + "\n"; 
paper_login +=  "URL GOTO=https://www.paper.id/webappv1/#/invoicer/finance/digital-payment-out/payout" + "\n"; 
paper_login +=  "WAIT SECONDS=3" + "\n"; 
paper_login +=  `EVENTS TYPE=KEYPRESS SELECTOR="input[name='email']" CHARS="laurabaker747@gmail.com"` + "\n"; 
paper_login +=  "TAG POS=1 TYPE=BUTTON ATTR=TXT:Selanjutnya" + "\n"; 
paper_login +=  "SET !ENCRYPTION NO" + "\n"; 
paper_login +=  `EVENTS TYPE=KEYPRESS SELECTOR="input[data-cy='password']" CHARS="Anak12345"` + "\n"; 
paper_login +=  "TAG POS=1 TYPE=BUTTON ATTR=TXT:Masuk" + "\n"; 
paper_login +=  "WAIT SECONDS=2" + "\n"; 
paper_login +=  "TAB OPEN" + "\n"; 
paper_login +=  "TAB T=2" + "\n"; 
paper_login +=  "TAB CLOSEALLOTHERS" + "\n"; 
paper_login +=  "TAB T=1" + "\n"; 
paper_login +=  "URL GOTO=https://www.paper.id/webappv1/#/invoicer/finance/digital-payment-out/payout" + "\n"; 
paper_login +=  "WAIT SECONDS=3" + "\n"; 