var macro;
macro =  "CODE:";
macro +=  `SET !DATASOURCE Template_Galaxy_Web.csv` + "\n"; 
macro +=  `SET !DATASOURCE_LINE {{i}}` + "\n"; 
macro +=  `TAB T=1` + "\n"; 
macro +=  `SET !REPLAYSPEED MEDIUM` + "\n"; 
macro +=  `SET !ERRORIGNORE YES` + "\n"; 
macro +=  `SET !EXTRACT_TEST_POPUP NO` + "\n"; 
macro +=  `URL GOTO=https://galaxyproperty.co.id/main/agent/add-secondary` + "\n"; 
macro +=  `WAIT SECONDS=1` + "\n"; 
macro +=  `EVENTS TYPE=KEYPRESS SELECTOR="#inputPrefix" CHARS={{!COL1}}` + "\n"; 
macro +=  `EVENTS TYPE=KEYPRESS SELECTOR="#inputTitle" CHARS={{!COL2}}` + "\n"; 
macro +=  `EVENT TYPE=CLICK SELECTOR="#inputCategory" BUTTON=0` + "\n"; 
macro +=  `EVENT TYPE=CLICK XPATH="//*[contains(text(),'{{!COL3}}')]" BUTTON=0` + "\n"; 
macro +=  `EVENT TYPE=CLICK SELECTOR="#inputTransaction" BUTTON=0` + "\n"; 
macro +=  `EVENT TYPE=CLICK XPATH="//*[contains(text(),'{{!COL4}}')]" BUTTON=0` + "\n"; 
macro +=  `EVENT TYPE=CLICK SELECTOR="#inputListingType" BUTTON=0` + "\n"; 
macro +=  `EVENT TYPE=CLICK XPATH="//*[contains(text(),'{{!COL5}}')]" BUTTON=0` + "\n"; 
macro +=  `EVENTS TYPE=KEYPRESS SELECTOR="#inputpriceview" CHARS={{!COL6}}` + "\n"; 
macro +=  `EVENT TYPE=CLICK SELECTOR="#inputCertificate" BUTTON=0` + "\n"; 
macro +=  `EVENT TYPE=CLICK XPATH="//option[text()='{{!COL7}}']" BUTTON=0` + "\n"; 
macro +=  `EVENTS TYPE=KEYPRESS SELECTOR="#inputDescription" CHARS={{!COL8}}` + "\n"; 
macro +=  `TAG POS=1 TYPE=A ATTR=TXT:Next` + "\n"; 
macro +=  `WAIT SECONDS=1` + "\n"; 
macro +=  `EVENTS TYPE=KEYPRESS SELECTOR="#inputLandArea" CHARS={{!COL9}}` + "\n"; 
macro +=  `EVENTS TYPE=KEYPRESS SELECTOR="#inputBuildingArea" CHARS={{!COL10}}` + "\n"; 
macro +=  `EVENTS TYPE=KEYPRESS SELECTOR="#inputWideArea" CHARS={{!COL11}}` + "\n"; 
macro +=  `EVENTS TYPE=KEYPRESS SELECTOR="#inputLongArea" CHARS={{!COL12}}` + "\n"; 
macro +=  `EVENT TYPE=CLICK SELECTOR="#inputToward" BUTTON=0` + "\n"; 
macro +=  `EVENT TYPE=CLICK XPATH="//option[text()='{{!COL13}}']" BUTTON=0` + "\n"; 
macro +=  `TAG POS=2 TYPE=A ATTR=TXT:Next` + "\n"; 
macro +=  `WAIT SECONDS=1` + "\n"; 
macro +=  `EVENT TYPE=CLICK SELECTOR="#inputFurnish" BUTTON=0` + "\n"; 
macro +=  `EVENT TYPE=CLICK XPATH="//option[text()='{{!COL14}}']" BUTTON=0` + "\n"; 
macro +=  `EVENT TYPE=KEYPRESS SELECTOR="#inputFloor" CHAR={{!COL15}}` + "\n"; 
macro +=  `EVENT TYPE=KEYPRESS SELECTOR="#inputBedroom" CHAR={{!COL16}}` + "\n"; 
macro +=  `EVENT TYPE=KEYPRESS SELECTOR="#inputBathroom" CHAR={{!COL17}}` + "\n"; 
macro +=  `EVENT TYPE=KEYPRESS SELECTOR="#inputAddBedroom" CHAR={{!COL18}}` + "\n"; 
macro +=  `EVENTS TYPE=KEYPRESS SELECTOR="#inputAddBathroom" CHARS={{!COL19}}` + "\n"; 
macro +=  `EVENT TYPE=CLICK SELECTOR="#inputWaterplan" BUTTON=0` + "\n"; 
macro +=  `EVENT TYPE=CLICK XPATH="//option[text()='{{!COL20}}']" BUTTON=0` + "\n"; 
macro +=  `EVENTS TYPE=KEYPRESS SELECTOR="#inputElectricity" CHARS={{!COL21}}` + "\n"; 
macro +=  `EVENTS TYPE=KEYPRESS SELECTOR="#inputGarage" CHARS={{!COL22}}` + "\n"; 
macro +=  `TAG POS=3 TYPE=A ATTR=TXT:Next` + "\n"; 
macro +=  `WAIT SECONDS=1` + "\n"; 
macro +=  `EVENT TYPE=CLICK SELECTOR="#inputProvince" BUTTON=0` + "\n"; 
macro +=  `EVENT TYPE=CLICK XPATH="//option[text()='{{!COL23}}']" BUTTON=0` + "\n"; 
macro +=  `WaIT SECONDS=1.5` + "\n"; 
macro +=  `EVENT TYPE=CLICK SELECTOR="#inputCity" BUTTON=0` + "\n"; 
macro +=  `EVENT TYPE=CLICK XPATH="//option[text()='{{!COL24}}']" BUTTON=0` + "\n"; 
macro +=  `WaIT SECONDS=1.5` + "\n"; 
macro +=  `EVENT TYPE=CLICK SELECTOR="#inputDistrict" BUTTON=0` + "\n"; 
macro +=  `EVENT TYPE=CLICK XPATH="//option[text()='{{!COL25}}']" BUTTON=0` + "\n"; 
macro +=  `EVENTS TYPE=KEYPRESS SELECTOR="#inputAddress" CHARS={{!COL26}}` + "\n"; 
macro +=  `EVENT TYPE=KEYPRESS SELECTOR="#inputBlok" CHAR={{!COL27}}` + "\n"; 
macro +=  `EVENTS TYPE=KEYPRESS SELECTOR="#inputNumberUnit" CHARS={{!COL28}}` + "\n"; 
macro +=  `TAG POS=4 TYPE=A ATTR=TXT:Next` + "\n"; 
macro +=  `SET !REPLAYSPEED FAST` + "\n"; 
macro +=  `WAIT SECONDS=1` + "\n"; 
macro +=  `EVENTS TYPE=KEYPRESS SELECTOR="#coagent\\[\\]" CHARS={{!COL29}}` + "\n"; 
macro +=  `WAIT SECONDS=1` + "\n"; 
macro +=  `EVENT TYPE=CLICK XPATH="//div[contains(text(),'{{!COL29}}')]" BUTTON=0` + "\n"; 
macro +=  `EVENT TYPE=CLICK SELECTOR="#btn-addproperty" BUTTON=0` + "\n"; 
macro +=  `WAIT SECONDS=1` + "\n"; 
macro +=  `TAG POS=1 TYPE=INPUT:FILE FORM=ID:add-design ATTR=ID:formFile CONTENT={{!COL30}}{{!COL31}}` + "\n"; 
macro +=  `TAG POS=1 TYPE=INPUT:FILE ATTR=NAME:inputPropertyImage[] CONTENT={{!COL30}}{{!COL32}}` + "\n"; 
macro +=  `WAIT SECONDS=3` + "\n"; 
macro +=  `TAG POS=1 TYPE=BUTTON ATTR=TXT:Submit` + "\n"; 
macro +=  `SET !VAR1 EVAL("var s='{{!COL33}}'; if(s.length > 1){var x=1;}else{var x=0;} x;")` + "\n"; 
macro +=  `TAG POS={{!VAR1}} TYPE=A ATTR=TXT:"*Upload Image*"` + "\n"; 
macro +=  `TAG POS={{!VAR1}} TYPE=INPUT:FILE ATTR=NAME:inputPropertyImage[] CONTENT={{!COL30}}{{!COL33}}` + "\n"; 
macro +=  `WAIT SECONDS={{!VAR1}} ` + "\n"; 
macro +=  `TAG POS={{!VAR1}} TYPE=BUTTON ATTR=TXT:Submit` + "\n"; 
macro +=  `SET !VAR1 EVAL("var s='{{!COL34}}'; if(s.length > 1){var x=1;}else{var x=0;} x;")` + "\n"; 
macro +=  `TAG POS={{!VAR1}} TYPE=A ATTR=TXT:"*Upload Image*"` + "\n"; 
macro +=  `TAG POS={{!VAR1}} TYPE=INPUT:FILE ATTR=NAME:inputPropertyImage[] CONTENT={{!COL30}}{{!COL34}}` + "\n"; 
macro +=  `WAIT SECONDS={{!VAR1}} ` + "\n"; 
macro +=  `TAG POS={{!VAR1}} TYPE=BUTTON ATTR=TXT:Submit` + "\n"; 
macro +=  `SET !VAR1 EVAL("var s='{{!COL35}}'; if(s.length > 1){var x=1;}else{var x=0;} x;")` + "\n"; 
macro +=  `TAG POS={{!VAR1}} TYPE=A ATTR=TXT:"*Upload Image*"` + "\n"; 
macro +=  `TAG POS={{!VAR1}} TYPE=INPUT:FILE ATTR=NAME:inputPropertyImage[] CONTENT={{!COL30}}{{!COL35}}` + "\n"; 
macro +=  `WAIT SECONDS={{!VAR1}} ` + "\n"; 
macro +=  `TAG POS={{!VAR1}} TYPE=BUTTON ATTR=TXT:Submit` + "\n"; 
macro +=  `WAIT SECONDS=2` + "\n"; 
macro +=  `TAG POS=1 TYPE=A ATTR=HREF:"*galaxyproperty.co.id/property/detail/*" EXTRACT=HREF` + "\n"; 
macro +=  `SET !REPLAYSPEED MEDIUM` + "\n"; 
macro +=  `URL GOTO=https://docs.google.com/forms/d/e/1FAIpQLSdSRUSRjEtjPhfNFmrd6i9WK10Ht5ovS5YjEXUMM0IZJs9GCA/viewform` + "\n"; 
macro +=  `EVENTS TYPE=KEYPRESS XPATH="(//input[@type='text'])[1]" CHARS={{!COL1}}` + "\n"; 
macro +=  `EVENTS TYPE=KEYPRESS XPATH="(//input[@type='text'])[2]" CHARS={{!EXTRACT}}` + "\n"; 
macro +=  `WAIT SECONDS=1` + "\n"; 
macro +=  `TAG POS=1 TYPE=DIV ATTR=ROLE:button` + "\n"; 
macro +=  `WAIT SECONDS=3` + "\n"; 

start = Number(prompt("Input start line (first line is 2 because 1 is header)", 2));
end = Number(prompt("Input end line"));

for(var i = start; i <= end; i++){
    iimSet('i', i);
    iimPlay(macro);
}